# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aztewoidz < Formula
  desc "aztewoidz
"
  homepage "https://github.com/aidanaden/aztewoidz"
  version "0.1.9"

  on_macos do
    on_intel do
      url "https://github.com/aidanaden/aztewoidz/releases/download/0.1.9/aztewoidz-0.1.9-darwin-amd64.tar.gz"
      sha256 "f7bead3a5ebe923795a5f85ec56305c155443458eeac53cf9d78e99ea0380f35"

      def install
        bin.install "aztewoidz"
      end
    end
    on_arm do
      url "https://github.com/aidanaden/aztewoidz/releases/download/0.1.9/aztewoidz-0.1.9-darwin-aarch64.tar.gz"
      sha256 "b5af63456cef2e90ce3f23782d776d83c1b4386fd8290c990aaf57b252af2837"

      def install
        bin.install "aztewoidz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aidanaden/aztewoidz/releases/download/0.1.9/aztewoidz-0.1.9-linux-amd64.tar.gz"
        sha256 "6380f9c316ec2513d57f7d911431059d68f2eb7201a68cee36af9e96754dab46"

        def install
          bin.install "aztewoidz"
        end
      end
    end
  end
end
