# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Aztewoidz < Formula
  desc "Asteroid game written with raylib in zig"
  homepage "https://github.com/aidanaden/aztewoidz"
  url "https://github.com/aidanaden/aztewoidz/archive/refs/tags/0.1.10.tar.gz"
  sha256 "3c225bebd35cf1a07a18192c0904e88ff4168499c91122573b9b630507afc1b0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aidanaden/aztewoidz/releases/download/0.1.10/aztewoidz-0.1.10-darwin-amd64.tar.gz"
      sha256 "9d2724cf94d51a74191536df482524b854ce4cc247bee0d64e79823b47c40639"
    end

    on_arm do
      url "https://github.com/aidanaden/aztewoidz/releases/download/0.1.10/aztewoidz-0.1.10-darwin-arm64.tar.gz"
      sha256 "13a125fec9efac9d2821ff82504a898dd2dbe91fce47cb79f307c370cd695f9e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aidanaden/aztewoidz/releases/download/0.1.10/aztewoidz-0.1.10-linux-amd64.tar.gz"
      sha256 "0969db1d035314f191db572c9fb8b6d072ea5298ea278a0851ca04945f0c8e01"
    end
  end

  def install
    bin.install "aztewoidz"
  end
end
