# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Aztewoidz < Formula
  include Language::Python::Virtualenv

  desc "Asteroid game written with raylib in zig"
  homepage "https://github.com/aidanaden/aztewoidz"
  url "https://github.com/aidanaden/aztewoidz/archive/refs/tags/0.1.10.tar.gz"
  sha256 "2eedc5c3ea1b936d053699ce57e6adca7c1937f7a869199fed9a80a89b6deb8c"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aidanaden/aztewoidz/releases/download/0.1.10/aztewoidz-0.1.10-darwin-amd64.tar.gz"
      sha256 "8226988826d781833a9459e2a24d6851e6d5c88c495a2df6ab17aebee62ec761"
    end

    on_arm do
      url "https://github.com/aidanaden/aztewoidz/releases/download/0.1.10/aztewoidz-0.1.10-darwin-arm64.tar.gz"
      sha256 "29eae0b73b6dc7b0326e8aad40746b59ef5bfc0521458c9678e59421d604cf42"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aidanaden/aztewoidz/releases/download/0.1.10/aztewoidz-0.1.10-linux-amd64.tar.gz"
      sha256 "4fdc68e04b308069f0ea1f80e8de6d22b625e284062cce4436c967485d8ccedc"
    end
  end

  def install
    bin.install "aztewoidz"
  end
end
